JupiterOne/graph-tenable-io

jest.config.js
src/executionHandler.test.ts
src/executionHandler.ts
src/utils/logObjectCounts.ts

A start to getting more info, produces the following log content:
```
graphEntityCounts: {
"accounts": 1,
"users": 1,
"assets": 2,
"scans": 2,
"vulnerabilities": 0,
"vulnerabilityFindings": 0,
"containers": 1,
"containerReports": 1,
"containerMalwares": 0,
"containerFindings": 3,
"containerUnwantedPrograms": 0
}
--
graphRelationshipCounts: {
"accountUserRelationships": 1,
"userScanRelationships": 2,
"scanVulnerabilityRelationships": 0,
"vulnerabilityFindingRelationships": 0,
"scanFindingRelationships": 0,
"scanAssetRelationships": 2,
"assetScanVulnerabilityRelationships": 0,
"accountContainerRelationships": 1,
"containerReportRelationships": 1,
"reportMalwareRelationships": 0,
"reportFindingRelationships": 3,
"reportUnwantedProgramRelationships": 0
}
--
tenableDataCounts: {
"assets": 2, …
```

Log object counts

---

src/executionHandler.ts
src/initializeContext.ts
src/invocationValidator.ts
src/persister/index.ts
src/tenable/TenableClient.test.ts
src/tenable/TenableClient.ts
src/tenable/types.ts

More logging, this time in the API client so we can see what is coming back from the API. There is no reason to suspect the operation generation since our previously added logging indicated there were no scan vulnerabilities, but we don't have a deep enough count to know why.

Add request logging information

---

src/executionHandler.ts
src/tenable/TenableClient.test.ts
src/tenable/TenableClient.ts
src/tenable/types.ts
test/fixtures/asset-vulnerability-info-not-found.json
test/fixtures/asset-vulnerability-info-ok.json

These changes address two issues:
1. When a scan is aborted, the details are blank, causing previously successful execution results to be wiped out during ingestion
2. Scan hosts with vulnerabilities might not have vulnerability details available
This latter issue seems to be, scans of type "ps" vulnerabilities do not have host-specific details available through the asset vulnerability APIs. Reviewing the vulnerabilities in the tenable UI, there are no details listed there either, so they don't appear to be available at all.

Fix errors

---

CHANGELOG.md
package.json
src/tenable/TenableClient.test.ts
src/tenable/TenableClient.ts

504 errors happen when the resulting server is too slow to respond to your request. Seems like a good idea to just try again if we get them to see if their servers respond faster next time. It might make sense to wait a second or so as well, but seems unnecessary to me.

AB#1723 - retry 504 errors

---

CHANGELOG.md
package.json
src/executionHandler.test.ts
src/executionHandler.ts
src/tenable/TenableClient.test.ts
src/tenable/TenableClient.ts

I set the log level=TRACE on infrastructure running this integration in order to expose logs about the API calls in this integration. However, the underlying SDK has a _ton_ of TRACE-level logging:
```
'_rawData not found'
'No changes detected'
'Found in old set'
'Calling handleSkippedDuplicate; Already seen in new set'
'[SKIP] - Relationships in new dataset have identical key'
'[SKIP] - Entities in new dataset have identical key'
'Calling diffRawData'
'_rawData deleted from item'
'Item _rawData differs from existing, keeping only changed properties'
'Calling handleUpdate'
'Calling uploadRawData'
'_rawData has changed'
'_rawData uploaded'
'Not found in new set, already marked _deleted'
'Calling handleDelete; Not found in new set'
'Executing raw query'
'Calling handleUpdate; No changes …
```

Improve logging

---

CHANGELOG.md
package.json

This is the release of the bulk export changes, it should help alleviate rate limiting problems we've had with a couple of the endpoints.

Graph tenable cloud v6.0.0

---

src/tenable/TenableClient.test.ts
src/tenable/TenableClient.ts
src/tenable/createAssetExportCache.ts
src/tenable/createVulnerabilityExportCache.ts
test/fixtures/vulnerabilities-not-found.json

It was reported that a customer was seeing a 404 in their integration job log. Investigating revealed that the Tenable API was returning 404s for `https://cloud.tenable.com/scans/scan_uuid/hosts/host_id` which is most likely because the hosts are older than 35 days. This should allow for job executions to complete until work is done to finish migrating the scan details endpoint to the export api and allow for ingestion of older data.

Handle tenable 404 for host vulnerabilities

---

CHANGELOG.md
src/executionHandler.test.ts
src/tenable/createAssetExportCache.ts
src/tenable/createVulnerabilityExportCache.ts
src/tenable/index.test.ts

Increase timeout for larger exports and give the status endpoint some breathing room (429 errors)

Increase export timeout and sleep between calls to export status

---

package.json
src/config.ts
src/tenable/TenableClient.test.ts
src/tenable/TenableClient.ts
src/tenable/__recordings__/cancelAssetExport_3552878987/recording.har
src/tenable/__recordings__/createAssetExportCache-timeout_2749653351/recording.har
src/tenable/__recordings__/createVulnerabilityExportCache-timeout_3111238685/recording.har
src/tenable/createAssetExportCache.ts
src/tenable/createVulnerabilityExportCache.ts
src/tenable/index.test.ts
src/tenable/types.ts
test/config.ts
test/recording.ts
yarn.lock

This primarily cleans up any _asset_ or _vuln_ export jobs that were started by the integration. It also replaces some relevant recordings with Polly recordings.

Clean up timed-out export jobs

---

CHANGELOG.md
src/tenable/TenableClient.ts

Fixes #97 
Tenable asks that integrations comply with their user agent header spec: http://stevemcgrath.io/post/2019-11-07-integration-ua-string-standard/
```
- Added `User-Agent` header to Tenable API calls.
```

Add User-Agent header to Tenable API calls

---

CHANGELOG.md
src/tenable/TenableClient.test.ts
src/tenable/TenableClient.ts
src/tenable/__recordings__/iterateAssets-success_1289501922/recording.har
src/tenable/createAssetExportCache.ts

This change sets us up for ingesting `Asset`s as entities, and not having to hold the entire asset cache in memory. The graph is unchanged.
```
- Added `TenableClient.iteraetAssets()` method. Made other asset export
endpoints private.
```

Add client.iterateAssets

---

CHANGELOG.md
docs/jupiterone.md
src/steps/vulnerabilities/index.ts

```
- Removed support for ingesting the following entities:
| Resources             | Entity `_type`                  | Entity `_class`         |
| --------------------- | ------------------------------- | ----------------------- |
| Scan                  | `tenable_scan`                  | `Assessment`, `Service` |
| Vulnerability Finding | `tenable_vulnerability_finding` | `Finding`               |
- Removed support for ingesting the following relationships:
| Source                          | \_class        | Target                          |
| ------------------------------- | -------------- | ------------------------------- |
| `tenable_scan`                  | **IDENTIFIED** | `tenable_vulnerability_finding` |
| `tenable_scan`                  | **IDENTIFIED** | …
```

Remove scan steps

---

src/steps/vulnerabilities/converters.ts
src/utils/targetEntities.ts

**Do not** create target `aws_instance`, `azure_vm`, or `google_compute_instance` entities if they do not exist.

Skip creating target `host` entities

---

CHANGELOG.md
src/steps/vulnerabilities/converters.ts

This PR fixes a bug where datetime properties on `tenable_asset` were strings instead of numbers.

[INT-3246] Dates Should Be Numbers

---

CHANGELOG.md
src/steps/vulnerabilities/converters.ts
src/tenable/client/types.ts

This PR adds `last_fixed` property to `tenable_vulnerability_finding`.
Best merged/reviewed after #190 as running Tenable integration from main without any changes resulted in some error for the vulnerability step which got fixed in #190.

INT-4493 - Tenable_vulnerability_finding Enhancement request

---

src/steps/vulnerabilities/converters.ts

This PR adds new properties to the `tenable_vulnerability_finding` entity:
- cvss3BaseScore
- cvss3TemporalScore
- cvssBaseScore
- cvssTemporalScore
- cvss3Vector
- cvssVector
- hasPatch

add vuln prioritization properties

---

CHANGELOG.md
package.json
src/steps/vulnerabilities/converters.ts
src/tenable/client/types.ts

The output property is often very large and contributing to a lot of memory/disk usage. I've removed it from raw data.
In the future if we find some use for this proeprty we can do more fine-grained trimming.

remove output property from raw data

---

CHANGELOG.md
package.json
src/steps/constants.ts

This PR disabled indexing metadata for relationships. The metadata for these relationships isn't used and takes up uneeded extra space.

do not index relationships metadata

---

src/steps/constants.ts

Disable index metadata for all mapped relationships to save disk space

disable index metadata for mapped relationships

---

src/tenable/TenableClient.ts

The bunyan logger does not serialize most properties on extended Errors. This log is here to make sure we can record and act on those properties.
I'm working seperately to fix this globally in the SDK.

always log error in handle errror

---

CHANGELOG.md
package.json
src/tenable/TenableClient.ts

This PR updates the retry logic for Tenable to attempt to retry 502 errors. It also adds a default delay of 3 seconds for non-429 retries.
The `IntegrationProivderAPIError` is also updates to proivide better messages about what errors happened (404, 503, etc.). Previoulsy it always used the message on the response body from Tenable. This message was always the same and didn't provide what went wrong.

updating tenable errors and retry logic

---

src/steps/vulnerabilities/converters.ts
src/tenable/client/types.ts

Adds the `unsupported_by_vendor` property to `tenble_vulnerability_finding`

add unsupportedByVendor property

---

.gitignore
src/steps/vulnerabilities/converters.test.ts
src/steps/vulnerabilities/converters.ts

A `fqdns` is a "Fully Qualified" dns identifier.  It indicates that this device had a connection some sort of larger network, most commonly the internet. Any macAddresses used by this device over the internet can be considered unique (even though it isn't necessarily the case) because it is standard in the industry. This PR pulls adds those new `fqdns` macAddresses to the `macAddresses` property of the `tenable_asset` record.

APP-15128 - Fetching more macAddresses

---

src/steps/agents/index.ts

This step was not creating relationships for some customers because the `agentUuid` property sometimes does not include hyphens.  This PR ensures that UUIDs are formatted prior to checking the jobState.

APP-15195 - Format uuids so that they are uniform
