src/tenable/fetchTenableData.ts

There was no waiting for all the work, so there would be different outcomes on each run 😱

Fix broken promises

---

package.json
src/initializeContext.ts
src/invocationValidator.ts
src/tenable/TenableClient.test.ts
src/tenable/TenableClient.ts
yarn.lock

This should help with 429 errors. Using the time we're told by Tenable to wait.

Retry requests based on Retry-After headers

---

src/converters/FindingEntityConverter.test.ts
src/converters/FindingEntityConverter.ts
src/converters/vulnerabilities.test.ts
src/converters/vulnerabilities.ts
src/jupiterone/entities/FindingEntity.ts
src/tenable/types.ts

These were obviously missing when I ran `find Finding with _integrationType="tenable-cloud"`.

Add a couple container finding properties

---

CHANGELOG.md

First release after migrating to the open-source integration framework.

Changelog for 7.0.0

---

CHANGELOG.md
package.json

```
- Added `displayName` property to entities
- Imported client from `@jupiterone/tenable-client-nodejs`.
- Added `User-Agent` header to Tenable API calls.
```

Changelog for 7.1.0

---

CHANGELOG.md
package.json

```
- Added support for ingesting the following **new** relationships:
| Source         | \_class   | Target                                                        |
| -------------- | --------- | ------------------------------------------------------------- |
| `tenable_scan` | **SCANS** | `aws_instance,azure_vm,google_compute_instance,tenable_asset` |
- Added `TenableClient.iterateAssets()` method. Made other asset export
endpoints private.
```

Changelog for 7.2.0

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/constants.ts
src/steps/scans/__recordings__/fetch-assets-mapped-relationships-azure_vm_3276337367/recording.har
src/steps/scans/converters.ts
src/steps/scans/index.test.ts
src/steps/scans/index.ts
yarn.lock

This is along the way of a refactor from:
to: 
per feedback from Tenable.

Add agent resources

---

docs/spec/src/access/index.ts
docs/spec/src/containers/index.ts
docs/spec/src/index.ts
docs/spec/src/types.ts
docs/spec/src/vulnerabilities/index.ts
package.json
src/steps/containers/index.ts
src/steps/users/index.ts
test/spec.test.ts

FWIW we are currently in the process of making a big conversion in this integration anyway, but it's a good opportunity to review the data model here.
Here's the J1 Vuln data model: https://support.jupiterone.io/hc/en-us/articles/360041429733-Data-Model-for-Vulnerability-Management
**Current**:
**Proposed**:

Add tenable spec

---

CHANGELOG.md
docs/jupiterone.md
package.json
yarn.lock

```
- Upgraded `@jupiterone/integration-sdk-*@6.18.0`

Sdk 6.18.0

---

CHANGELOG.md
docs/jupiterone.md
docs/spec/src/vulnerabilities/index.ts
src/constants.ts

It does what it says on the box

Retype tenable_vulnerability -> tenable_vulnerability_finding

---

CHANGELOG.md
package.json

```
- Added support for ingesting the following **new** entities:
| Resources | Entity `_type`  | Entity `_class` |
| --------- | --------------- | --------------- |
| Asset     | `tenable_asset` | `HostAgent`     |
- Added support for ingesting the following **new** relationships:
| Source            | \_class | Target                          |
| ----------------- | ------- | ------------------------------- |
| `tenable_account` | **HAS** | `tenable_asset`                 |
| `tenable_asset`   | **HAS** | `tenable_vulnerability_finding` |
- Added support for ingesting the following **new** mapped relationships:
| Source                          | \_class | Target                          |
| ------------------------------- | ------- | ------------------------------- |
| `tenable_asset` …
```

Release 8.0.0

---

CHANGELOG.md
package.json
src/steps/vulnerabilities/converters.ts
src/steps/vulnerabilities/index.ts

```
- Prevent duplicate keys for `tenable_asset` entities
- Prevent duplicate keys for `tenable_vulnerability_finding` entities
- Prevent `Cannot read property 'map' of undefined` when iterating CVEs for
`tenable_vulnerability_finding`

Fix production errors

---

CHANGELOG.md
package.json
src/tenable/TenableClient.ts

I'm _hoping_ that this will simply publish the new version to our NPM org. I always anticipate some odd behavior with NPM. 🤞

Int 2132 rename npm package tenable io

---

CHANGELOG.md
package.json
src/steps/vulnerabilities/converters.ts
yarn.lock

This PR adds exploit-related properties to the Vulnerability entity.
Changes:
- `tenable-client-nodejs` version bumped to `v0.1.3`
- Exploit properties added to the `assign` portion of `Vulnerability` entity
- added in `createVulnerabilityEntity`

[INT-2707] Adding exploit related properties to Vulnerability entity.

---

.github/workflows/codeql-analysis.yml
CHANGELOG.md
src/steps/vulnerabilities/converters.ts

int 6502 fix severity property

---

.prettierignore
docs/tenable-cloud/tenable-api-exploration-2023-01-23.md

This PR adds a summary of relevant Tenable API endpoints, captures of rawData, and mappings to existing and potential entities.

Add Tenable API Exploration Docs

---

src/index.ts
src/invocationValidator.test.ts
src/invocationValidator.ts
src/steps/access/index.ts
src/steps/account/index.ts
src/steps/account/util.ts
src/steps/containers/index.ts
src/steps/index.ts
src/steps/service/index.ts
src/steps/vulnerabilities/index.ts

Additional refactoring and renaming for `getAccount`, `invocationValidator` -> `validateInvocation` and `integrationSteps`.

mv getAccount, integrationSteps, invocationValidator

---

src/tenable/TenableClient.ts

This PR extends the default timeout for tenable export steps

extend default timeout to 3 hours

---

src/steps/containers/index.ts

This PR fixes various duplicate key issues in the tenable container reports step.

fix duplicate relationships for tenable

---

docs/jupiterone.md
src/steps/agents/__recordings__/fetch-agents_730038084/recording.har
src/steps/agents/converters.ts
src/steps/agents/index.test.ts
src/steps/agents/index.ts
src/steps/constants.ts
src/steps/index.ts
src/steps/scanners/__recordings__/fetch-scanner-ids_2913282731/recording.har
src/steps/scanners/constants.ts
src/steps/scanners/index.test.ts
src/steps/scanners/index.ts
src/tenable/TenableClient.ts
src/tenable/client/index.ts
src/tenable/client/types.ts
test/config.ts
test/recording.ts

Ingest Agent Entity
Added scanner step to collect the ids to be used to fetch the agents
Added relationship Account HAS Agent

Ingest Agent Entity

---

src/steps/containers/index.ts

skipping duplicate relationship _key's

skip duplicate relationship keys

---

docs/jupiterone.md

This PR updates the documenation for the tenable.io integraiton.

update tenable documenation

---

CHANGELOG.md
package.json

- A new target added to create a relationship between `tenable_vulnerability_finding `and `vsphere_host`.

Release v9.3.5
